title: Official Media Bias/Fact Check Extension
markdown: kramdown
layout: default
comments: true
disqus: mbfcext

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty

# Setup
description: "Homepage of the Official Media Bias/Fact Check Extension."
url: https://drmikecrowe.github.io/mbfcext/
baseurl: "/mbfcext"

# About/contact
author:
    name: Mike Crowe
    url: https://github.com/drmikecrowe
    email: drmikecrowe@gmail.com

github:
    repo: https://github.com/drmikecrowe/mbfcext
# Custom vars
version: 3.0.0

pages_list:
    "Home": /mbfcext/
    "Release Notes": /mbfcext/releases/
    "Privacy Policy": /mbfcext/privacy/
    "Terms and Conditions": /mbfcext/terms/

extension_list:
    "Chrome Extension": https://chrome.google.com/webstore/detail/official-media-biasfact-c/ganicjnkcddicfioohdaegodjodcbkkh
    "Firefox Extension": https://addons.mozilla.org/en-US/firefox/addon/facebook-media-bias-extension/
