name: "Submit to Web Store"
on:
  push:
    branches:
      - main

#  workflow_dispatch:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build and package Chrome + Firefox
        run: pnpm package:all
      - name: Upload Chrome artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-mv3-prod
          path: build/chrome-mv3-prod.zip
      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-mv3-prod
          path: build/firefox-mv3-prod.zip
