name: 'Submit to Web Store'
on:
  workflow_dispatch:

#   push:
#     branches:
#     - release/*

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: DerYeger/pnpm-setup-action@master
        with:
          node-version: 18
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: DerYeger/pnpm-setup-action@master
        with:
          node-version: 18
      - run: pnpm build
      
  submit:
    name: Submit
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          chrome-file: build/chrome-mv3-prod.zip
